### ISSUE TITLE
scsynth crash on serverside alloc

### ISSUE THREAD

**Issue by salkin-mada** [flucoma/flucoma-sc#81]
Platform: **Arch  5.16.14-arch1-1 #1 SMP PREEMPT** Linux x86_64
SC ver: **3.12.2**
Flucoma-sc ver: **1.0.0-TB2.beta5** _I have also tested with building from source 10 mins ago, same crash_

The following happens when evaluating `FluidDataSet(s)`
Using: `sudo gdb scsynth -p $(ps -C scsynth -o pid h)`
```
Reading symbols from scsynth...
(No debugging symbols found in scsynth)
Attaching to program: /usr/bin/scsynth, process 67445
[New LWP 67448]
[New LWP 67451]
[New LWP 67452]
[New LWP 67453]
[New LWP 67454]
[New LWP 67455]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007effa4b4715a in __futex_abstimed_wait_common () from /usr/lib/libc.so.6
(gdb) n
Single stepping until exit from function __futex_abstimed_wait_common,
which has no line number information.

Thread 4 "scsynth" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7eff709fe640 (LWP 67452)]
0x000055e96cbb8d08 in ?? ()
(gdb) n
Cannot find bounds of current function
(gdb) bt
#0  0x000055e96cbb8d08 in ?? ()
#1  0x00007eff8d2e19b6 in ?? () from /usr/share/SuperCollider/Extensions/FluidCorpusManipulation/plugins/FluidManipulation.so
#2  0x00007eff8d423eac in ?? () from /usr/share/SuperCollider/Extensions/FluidCorpusManipulation/plugins/FluidManipulation.so
#3  0x00007effa4f56e3f in ?? () from /usr/lib/libscsynth.so.1
#4  0x00007effa4f3e1eb in ?? () from /usr/lib/libscsynth.so.1
#5  0x00007effa4db74d4 in std::execute_native_thread_routine (__p=0x55e96bc17b10) at /usr/src/debug/gcc/libstdc++-v3/src/c++11/thread.cc:82
#6  0x00007effa4b4a5c2 in start_thread () from /usr/lib/libc.so.6
#7  0x00007effa4bcf584 in clone () from /usr/lib/libc.so.6
```

Similarly this happens with several classes, ex. `FluidBufOnsetSlice.process(s, ...)`

**Comment by salkin-mada** [comment]
further back trace on FluidManipulation.so breakp # 1 and # 2:
```
#1  0x00007fbb684e1677 in fluid::client::impl::NonRealTime<fluid::client::NRTThreadingAdaptor<fluid::client::NRTSharedInstanceAdaptor<fluid::client::dataset::DataSetClient>
 >, fluid::client::FluidSCWrapper<fluid::client::NRTThreadingAdaptor<fluid::client::NRTSharedInstanceAdaptor<fluid::client::dataset::DataSetClient> > > >::NRTCommand::sendR
eply(char const*, bool) () from /home/salkin/.local/share/SuperCollider/Extensions/FluidCorpusManipulation/Plugins/FluidManipulation.so
#2  0x00007fbb6863116c in fluid::client::impl::NonRealTime<fluid::client::NRTThreadingAdaptor<fluid::client::NRTSharedInstanceAdaptor<fluid::client::dataset::DataSetClient>
 >, fluid::client::FluidSCWrapper<fluid::client::NRTThreadingAdaptor<fluid::client::NRTSharedInstanceAdaptor<fluid::client::dataset::DataSetClient> > > >::CommandNew::stage
2(World*) () from /home/salkin/.local/share/SuperCollider/Extensions/FluidCorpusManipulation/Plugins/FluidManipulation.so
```

**Comment by salkin-mada** [comment]
same happens with a build from the **dev** branch

**Comment by tremblap** [comment]
Hello! If you compile with code in Test instead of Release, you can get a source code line where the crash happens. In this compiler flag you have speed almost as good as Release but with some of the advantages of Debug.

**Comment by salkin-mada** [comment]
Here with a `--config Test` build (main branch)
```
#1  0x00007f975015c3d1 in fluid::client::impl::NonRealTime<fluid::client::NRTThreadingAdaptor<fluid::client::NRTSharedInstanceAdaptor<fluid::client::dataset::DataSetClient>
 >, fluid::client::FluidSCWrapper<fluid::client::NRTThreadingAdaptor<fluid::client::NRTSharedInstanceAdaptor<fluid::client::dataset::DataSetClient> > > >::NRTCommand::sendR
eply (this=this@entry=0x7f97387fc1c0, name=0x561065216150 "FluidDataSet/new", success=success@entry=true) at /usr/share/supercollider-headers/common/scsynthsend.h:123
#2  0x00007f97502519e9 in fluid::client::impl::NonRealTime<fluid::client::NRTThreadingAdaptor<fluid::client::NRTSharedInstanceAdaptor<fluid::client::dataset::DataSetClient>
 >, fluid::client::FluidSCWrapper<fluid::client::NRTThreadingAdaptor<fluid::client::NRTSharedInstanceAdaptor<fluid::client::dataset::DataSetClient> > > >::CommandNew::stage
2 (this=0x7f97387fc1c0, w=<optimized out>) at /usr/include/c++/11.2.0/bits/basic_string.h:194
#3  0x00007f975f0a4e3f in ?? () from /usr/lib/libscsynth.so.1
#4  0x00007f975f08c1eb in ?? () from /usr/lib/libscsynth.so.1
#5  0x00007f975ef054d4 in std::execute_native_thread_routine (__p=0x561065576350) at /usr/src/debug/gcc/libstdc++-v3/src/c++11/thread.cc:82
#6  0x00007f975ec985c2 in start_thread () from /usr/lib/libc.so.6
#7  0x00007f975ed1d584 in clone () from /usr/lib/libc.so.6

```

**Comment by salkin-mada** [comment]
Here with a `Debug` build, pointing to `NonRealtime.hpp:241` and SendReply.
Maybe the msg length is a hint? @weefuzzy 

```
#0  0x00005571cd8d01c8 in ?? ()
#1  0x00007ff5065bbad7 in SendReply (inReplyAddr=0x7ff4d4000b70, inBuf=0x7ff4ed46da74 "/FluidDataSet/new", inSize=32)
    at /usr/share/supercollider-headers/common/SC_ReplyImpl.hpp:47
#2  0x00007ff5065b9bee in fluid::client::SendReply (inReplyAddr=0x7ff4d4000b70, inBuf=0x7ff4ed46da74 "/FluidDataSet/new", inSize=32)
    at /tmp/flucoma-sc/include/wrapper/CopyReplyAddress.cpp:46
#3  0x00007ff5061ac693 in fluid::client::impl::NonRealTime<fluid::client::NRTThreadingAdaptor<fluid::client::NRTSharedInstanceAdaptor<fluid::clie
nt::dataset::DataSetClient> >, fluid::client::FluidSCWrapper<fluid::client::NRTThreadingAdaptor<fluid::client::NRTSharedInstanceAdaptor<fluid::cl
ient::dataset::DataSetClient> > > >::NRTCommand::sendReply (this=0x7ff4ee4714c0, name=0x5571cc723150 "FluidDataSet/new", success=true) at /tmp/fl
ucoma-sc/src/FluidManipulation/../../include/wrapper/NonRealtime.hpp:241
#4  0x00007ff506162b35 in fluid::client::impl::NonRealTime<fluid::client::NRTThreadingAdaptor<fluid::client::NRTSharedInstanceAdaptor<fluid::clie
nt::dataset::DataSetClient> >, fluid::client::FluidSCWrapper<fluid::client::NRTThreadingAdaptor<fluid::client::NRTSharedInstanceAdaptor<fluid::cl
ient::dataset::DataSetClient> > > >::CommandNew::stage2 (this=0x7ff4ee4714c0, w=0x5571cc810b80) at /tmp/flucoma-sc/src/FluidManipulation/../../in
clude/wrapper/NonRealtime.hpp:292
#5  0x00007ff50613047f in fluid::client::impl::NonRealTime<fluid::client::NRTThreadingAdaptor<fluid::client::NRTSharedInstanceAdaptor<fluid::clie
nt::dataset::DataSetClient> >, fluid::client::FluidSCWrapper<fluid::client::NRTThreadingAdaptor<fluid::client::NRTSharedInstanceAdaptor<fluid::cl
ient::dataset::DataSetClient> > > >::runAsyncCommand<fluid::client::impl::NonRealTime<fluid::client::NRTThreadingAdaptor<fluid::client::NRTShared
```

Hi, Owen.. :) Niklas here. Thanks for last time in November.

**Comment by jamesb93** [comment]
🍿

**Comment by weefuzzy** [comment]
I would guess that this is the same issue as before: SC and Flucoma being built with different versions of boost. Did you build Flucoma yourself, and did you set pass `-DSYSTEM_BOOST` to CMake?

**Comment by salkin-mada** [comment]
@elgiano, here next to me :) -> is compiling on a sc-header fork. Also on Arch. There no crash occurs. Now trying to build with the sc dev branch, to test further.

**Comment by salkin-mada** [comment]
@weefuzzy Nope - neither the Aur PKGBUILD or my own `cmake -G Ninja "Multi-Config"` endeavours included/includes setting `-DSYSTEM_BOOST`. I will make a new Debug build with that cmake addition.

**Comment by salkin-mada** [comment]
And yes sorry, I tried with the prebuilt release and I also build it myself.

**Comment by weefuzzy** [comment]
Ok, fingers crossed that's the problem: if the AUR Supercollider uses the system boost, Flucoma must also. 

I think the full options to add is `-DSYSTEM_BOOST=On`

**Comment by salkin-mada** [comment]
Okay! I just built against develop SC headers and and system boost. And it now works!
I will just check with the main branch again.

**Comment by jamesb93** [comment]
I'll look into adding that as a possibility to our builds as it could help debug things before they go wrong in workshops 🙃

**Comment by salkin-mada** [comment]
@weefuzzy good points. Its the Arch way, trouble trouble + build it locally :). Thank you for the DSYSTEM_BOOST lead. And for the all the wonderful work! **<3**

**Comment by madskjeldgaard** [comment]
Maybe this is worth mentioning in the readme ? I will update the aur package soon

**Comment by madskjeldgaard** [comment]
The system boost library stuff has been updated/implemented in the aur package `supercollider-flucoma-git` and it seems to work fine here. 

https://aur.archlinux.org/packages/supercollider-flucoma-git

**Comment by elgiano** [comment]
I just want to add that I managed to compile and run flucoma-sc against the latest SC develop branch. 
The key was to compile both with SYSTEM_BOOST.

thanks @salkin-mada and  @weefuzzy for the support and @madskjeldgaard for the AUR package!
